{% set name = "tcpypi" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tcpypi-{{ version }}.tar.gz
  sha256: 3691daed05a7d0c01ff365850feba87d8d0287ccbf4848126b72a99e93b61cf9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=0.16.2
    - numba >=0.51.2
    - numpy >=1.19.5

test:
  imports:
    - tcpyPI
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/dgilford/tcpyPI
  summary: 'tcpyPI: Tropical cyclone potential intensity calculations in Python'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - dgilford
